### ISSUE TITLE
This repository needs a good README.md file

### ISSUE THREAD

**Issue by THEOPHILEACHIZA** [THEOPHILEACHIZA/My-first-tutorial-project#1]
This repository needs a good README.md file

**Comment by MichaelKentBurns** [comment]
This is looking good.
You are following the directions, learning from other resources how to use GitHub projects.  You have created an issue to show your next step, and you are taking those steps and making commits.  

Excellent!

**Comment by THEOPHILEACHIZA** [comment]
thank you !

**Comment by MichaelKentBurns** [comment]
You have not properly completed this issue.
Yes, you have a README.md file but Step 13 of the task suggests:

First, read this article from FreeCodeCamp about ‘[How to Write a good README File for Your GitHub Project.](https://www.freecodecamp.org/news/how-to-write-a-good-readme-file/)‘ It is especially important to do this step well. You will also want to put a link to your GitHub repository in your Upwork profile.

Please make an effort to complete that step.     Anyone who looks at your project will not read far without a good README.     Also, anyone who wants to try your code will need a complete README.  

This is especially important for your first project, one that you want to highlight in your profile.
