### ISSUE TITLE
Write the Readme file

### ISSUE THREAD

**Issue by THEOPHILEACHIZA** [THEOPHILEACHIZA/My-first-tutorial-project#7]
I will write my Readme file, the techniques used, the process i used to build this web page and the new things i learned while building this web page.

**Comment by MichaelKentBurns** [comment]
Ah!  Sorry I did not see this new issue because you just added it while I was reopening the original issue about the README.     Please look at my comments on that issue and feel free to close one of these.   

Keep up the good work!

**Comment by THEOPHILEACHIZA** [comment]
Thanks, I will!
Théophile
Video editor

Le mer. 2 oct. 2024, 18:25, Michael Kent Burns ***@***.***> a
écrit :

**Comment by THEOPHILEACHIZA** [comment]
i modified my Readme file
