### ISSUE TITLE
socials media icons are not visible

### ISSUE THREAD

**Issue by bahati7** [THEOPHILEACHIZA/My-first-tutorial-project#8]
Overall, your project looks good, you're making progress. Please check your social media icons as they are not visible on my screen. also trying to enlarge the text to match the original design.

**Comment by THEOPHILEACHIZA** [comment]
Thank you for raising this issue! I resolved it by integrating Boxicons for social media icons, which now offers over 1 600 high-quality icons. Please test this solution and let me know if you encounter any further issues.

**Comment by bahati7** [comment]
Great
